### ISSUE TITLE
Expected a 'cuda' device type for generator but found 'cpu'

### ISSUE THREAD

**Issue by JonnesLin** [lywang3081/AFEC#4]
Hi,

When I ran the following command: python ./main.py --dataset CUB200 --trainer ewc --lamb 40 --lamb_emp 0.001, an error happened: Expected a 'cuda' device type for generator but found 'cpu'

Could you help me to figure it out? Thank you very much!

**Comment by lywang3081** [comment]
Hi, could you show more details about this bug?

BTW, from my experience, it is possibly caused by the cuda version and might be addressed by replacing "kwargs = {'num_workers': 8, 'pin_memory': True}" into "kwargs = {'num_workers': 0, 'pin_memory': False}" in main.py line 123 and afec_ewc.py line 93.

**Comment by JonnesLin** [comment]
ahhh that works for me. Thank u!

**Comment by JonnesLin** [comment]
Ahhhh it doesn't work

**Comment by lywang3081** [comment]
Could you provide more details about it?
